Feat : 나무 숲 스타일링
YAPP-Github/20th-Web-Team-1-FE pull request #10
Opened 2022-06-12 11:24 UTC by youngminss

### 💡 다음 이슈를 해결했어요.

- #6 

<br><br>

### 💡 이슈를 처리하면서 추가된 코드가 있어요.

1. `eslint.json` 파일에 대한 VSCode 상에 Dependency Error 가 지속적으로 발생되어 원인이 되는 의존성 패키지들을 설치된 것이 있습니다.

```bash
@typescript-eslint/eslint-plugin
@typescript-eslint/parser
eslint-plugin-react-hooks
eslint-plugin-react
eslint-plugin-prettier
eslint-config-prettier
```

  - 관련되어서 새로운 패키지를 설치하는 과정에서 yarnberry 관련 파일들 변경사항들이 현재 PR 내용에 많이 포함이 된 것 같습니다. 참고 부탁드리고 뭔가 이상하다고 생각하는 부분이 있다면 comment 부탁드립니다.

<br><br>

### 💡 필요한 후속작업이 있어요.

- `알림나무` 상단에 꿀벌 메시지 레이아웃을 `나무 편집` 상단에 재사용하려고 합니다. 

  - @leechoiswim1 님이 저번에 작업이 완료된 것으로 알고 있습니다.
  - PR 올리시면 관련 코드 재사용성을 고려해보고 적용하겠습니다.
  - 나무 편집에서 필요한 꿀벌 메시지 영역은 단순 메시지만 보여주는 영역이라, 지금 당장 급한 기능은 아닙니다.

- 구현 중에 `color system` 이슈와 관련하여, 제가 `theme.ts` 에 있는 컬러 코드 값을 변경하겠다고 했습니다.

  - 가장 최근 PR 이 반영된 `upstream` 기준으로, @numeru 님의 구현 부분의 styled 파일 내에 컬러 값이 변경 코드에 맞게 반영이 되지 않았습니다. 제가 수정하다가 놓치는 부분이 있을 것 같아서 건들지 않았습니다.
  - 따라서, 이번 PR 이 Merge 된 후에 Pull 받은 이후에 기존에 color styled 적용된 곳에 코드만 수정하시면 될 것 같습니다.

<br><br>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [x] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.

2022-06-13 04:15 UTC, numeru commented on src/pages/Trees/index.tsx
> +	const handleCloseForm = () => {
나무숲 페이지에서 처음 보이는 나무 리스트 화면과 플러스 버튼을 눌었을 때 나오는 나무 추가 화면을 state에 따라 바뀌어 보이게 하신 것 같은데,
아예 페이지를 분리하여 라우트를 시키지 않고, 하나의 페이지에서 관리하시는 이유가 있으실까요?

저는 페이지를 분리하는게 관리하는 state와 하위 컴포넌트로 전달되는 props가 줄어서 조금 더 간단하고 자연스럽지 않을까 생각합니다!

2022-06-13 04:15 UTC, numeru commented on src/components/shared/Chip/MessageChip/type.ts
> +}
컴포넌트의 props 타입을 지정하실 때 타입 이름을 `컴포넌트 이름` + `Type` 으로 이름을 작성하시는 것 같습니다.
그런데 타입 이름을 처음 봤을 때 컴포넌트 props의 타입보다는 MessageChip이 종류에 따른 타입이 있는 것 같은 느낌이 들어서 Props 라는 단어가 중간에 추가되는건 어떨까 싶습니다. (ButtonType 도 그렇구요.)

저는 그래서 컴포넌트 props의 타입은 다른 파일에서 가져오지 않고, 해당 컴포넌트 내에서 `Props` 라는 이름으로 통일해서 짓고 있습니다!

2022-06-13 04:15 UTC, numeru commented on src/components/shared/Chip/MessageChip/MessageChip.styled.ts
> +	margin: auto;
이 컴포넌트를 포함해 여러 컴포넌트들의 `width`를 `326px`로 지정하신 것 같습니다.
피그마 상에 그렇게 되어 있기는 하지만 회면이 늘어남에 따라 같이 늘어나는 것들은 `width: 100%` 으로 하는 것이 자연스러울 것 같은데, 일단 반응형은 나중으로 하고 구현만 하신 것인지는 몰라서 일단 언급만 드려 봅니다!

2022-06-13 04:15 UTC, numeru commented on src/components/shared/Button/type.ts
> +	children?: React.ReactNode;
이렇게 타입을 확장시키는 방식 좋은 것 같습니다!
`onClick`과 `children`은 무조건 받아야 하니 `?(optional)` 말고 필수로 하는 것도 좋아보입니다!

2022-06-13 04:15 UTC, numeru commented on src/components/shared/Button/Button.styled.ts
> +	color: ${(props) => (props.bgColor === 'primary' ? props.theme.colors.bt_white : props.theme.colors.bt_grey[50])};
`props`의 depth가 꽤 깊어서 모두 `props.` 으로 시작하는 것 보다 비구조화 할당으로 `({bgColor, theme})` 으로 하시면 코드가 조금 더 간결해질 것 같습니다!

2022-06-13 04:15 UTC, numeru commented on src/components/features/Trees/TreeList/TreeItem/TreeItemView.tsx
> +			<TreeShapeContainer size="small">
`TreeItem` 컴포넌트는 클릭 시 해당 나무의 상세 페이지로 이동하는 것으로 알고 있는데,
그렇다면 주소가 이동하는 것이므로 추후에 `<S.ItemWrapper>` 안을 `<Link>`로 한번 감싸주어야 할 것 같습니다!

나중에 더 기능이 구현되면 하실 것 같지만, 스타일이 망가질 수 있어서 미리 말씀드려요!

2022-06-13 04:15 UTC, numeru commented on src/components/features/Trees/TreeList/TreeItemAdd/TreeItemAddView.tsx
> +				<span className="plus-shape-bar row" />
나무를 추가하는 플러스 버튼인 것 같습니다!
그렇다면 유저가 클릭하고 동작이 수행되는 상호작용이 일어나기 때문에 `button` 태그를 사용하시는 것이 맞을 것 같습니다!

2022-06-13 04:28 UTC, numeru requested changes
수고 많으셨습니다!
제가 잘못 눌러서 리뷰가 분할되었네요.
저도 일단 request changes로 두겠습니다!
적어둔 리뷰는 편하게 고려 해주시고 같은 생각이시면 수정하신 뒤 merge 부탁드려요!

2022-06-13 04:28 UTC, numeru commented on src/components/features/Trees/TreeAddForm/Input/TreeNameInput/index.tsx
> +		onChangeTreeName(treeName);
`event: React.FormEvent<HTMLFormElement>` 로 하시면 아래 `(event.target as HTMLInputElement)` 로 다시 지정하시지 않아도 됩니다!

2022-06-13 04:37 UTC, numeru commented on src/components/shared/Button/Button.styled.ts
> +	color: ${(props) => (props.bgColor === 'primary' ? props.theme.colors.bt_white : props.theme.colors.bt_grey[50])};
`outline: 0`이 웹 접근성 상 좋지 않은 것으로 알고 있습니다!
아래 관련 링크 첨부드립니다

https://hohoya33.tistory.com/93

2022-06-19 18:04 UTC, youngminss commented on src/components/features/Trees/TreeAddForm/Input/TreeNameInput/index.tsx
> +		onChangeTreeName(treeName);
추가적으로 단순히 event.target 으로 사용하지 않고, event.cuurentTarget 으로 접근해야 해당 이벤트가 등록된 요소에 정확히 접근하기 때문에 비로소 Type Assertion 을 적용하지 않아도 value 속성에 정상적으로 접근할 수 있는 것 같습니다.

2022-06-19 18:07 UTC, youngminss commented on src/components/features/Trees/TreeList/TreeItemAdd/TreeItemAddView.tsx
> +				<span className="plus-shape-bar row" />
button 태그가 onClick 이벤트에도 적절한 건 맞는 것 같습니다.
내부 + 모양은 img 를 사용해도 되긴 하지만, 충분히 CSS 로도 가능한 부분이라 굳이 이미지를 사용해야 할까 싶습니다.

웹 접근성 측면은 저도 잘 모르지만, div 컨테이너 형태에서 가능한 방식을 생각해보고 적용해보겠습니다. 감사합니다.

2022-06-19 18:09 UTC, youngminss commented on src/components/shared/Button/Button.styled.ts
> +	color: ${(props) => (props.bgColor === 'primary' ? props.theme.colors.bt_white : props.theme.colors.bt_grey[50])};
`:focuis-visible` 방식이 아직 까진 브라우저 호환이 엄청 좋은 것 같진 않아서 조금 걸립니다.
`:focuis-visible` 방식이 아닌, 이전에 다른 방식들이 여럿 소개 되는 것 같은데, 저도 웹 접근성 부분은 더 조사해보고, 먼저 프로젝트 완성도가 보이면 추가적으로 신경 써보겠습니다.

2022-06-19 18:11 UTC, youngminss commented on src/components/shared/Button/type.ts
> +	children?: React.ReactNode;
버튼이 꼭 onClick 이벤트를 수행해야하는 건 아닐 때도 있다고 생각했습니다.
예를 들어, type 이 submit 이고 submit 버튼에 해당하는 onSubmit 이벤트를 form 에 등록되어 있다고 했을 때는 onClick 이벤트가 작동해야 되는 것이 아닌 것 처럼요.

혹시 제가 잘 못 사용하고 있는 방식 같다면, 추가적인 첨언 부탁드립니다 ! 🙇‍♂️

2022-06-19 18:17 UTC, youngminss commented on src/pages/Trees/index.tsx
> +	const handleCloseForm = () => {
말씀하신 것처럼, 생각을 해보니 굳이 state 로 나무 편집 창 전환을 관리할 필요가 있을까 ? 라는 생각이 들었습니다.
해당 state 하나 때문에 dependency 가 생기는 컴포넌트들이 여럿 생겨서 좋아 보이지 않은 것 같습니다.

초기에 state 로 관리하려 했던 이유는, 나무 정보 편집하는 부분이 독립된 페이지 느낌까지는 생각이 들지 않아서 조건부 렌더링가 적절하다고 생각하게 되었습니다. 

구현을 하고나서 영광님 피드백을 듣고 반영해보니 라우팅이 훨씬 간단하다고 생각이 바뀌었습니다. 감사합니다 😎

2022-06-19 18:18 UTC, youngminss commented on src/components/shared/Chip/MessageChip/type.ts
> +}
참고하겠습니다.

이 부분은 저도 Type 네이밍이나 컴포넌트별 Type 을 어떻게 관리하는 게 좋을 지 아직 고민이 되서, 좀 더 고민해보고 아니다 싶으면 말씀해주신 방향대로 적용해보겠습니다.

2022-06-20 02:12 UTC, numeru commented on src/components/shared/Button/type.ts
> +	children?: React.ReactNode;
생각해보니 말씀해주신 상황도 있을 것 같습니다!
`onClick` 은 필수가 아니어도 괜찮겠네요

2022-06-20 02:16 UTC, numeru commented on src/components/shared/Button/Button.styled.ts
> +	color: ${(props) => (props.bgColor === 'primary' ? props.theme.colors.bt_white : props.theme.colors.bt_grey[50])};
저도 `outline: 0` 이 접근성 상 좋지 않다고만 알고 있는데, 대체 방식으로 `:focuis-visible` 이 괜찮을지는 써봐야 알 것 같네요.
일단 기능 위주로 개발하고, 프로젝트 하면서 웹 접근성도 같이 고민해보는 느낌으로 가면 좋을 것 같아요!

2022-06-20 02:18 UTC, numeru commented on src/components/features/Trees/TreeList/TreeItemAdd/TreeItemAddView.tsx
> +				<span className="plus-shape-bar row" />
네 저도 css로 가능한건 굳이 이미지를 쓰지 않는 것도 좋다고 생각합니다!
하나의 관점만 말씀 드린 것이고, 지금 이렇게 가도 충분히 좋습니다!

2022-06-20 02:19 UTC, numeru approved these changes
고생많으셨습니다!

2022-06-20 02:19 UTC, merged