[#78] Feat : 메세지함 무한스크롤 추가
YAPP-Github/20th-Web-Team-1-FE pull request #107
Opened 2022-07-22 17:04 UTC by leechoiswim1

### 💡 다음 이슈를 해결했어요.

#78 

<br><br>

### 💡 필요한 후속작업이 있어요.

- 메세지함 데이터 요청 후 처리중입니다.   전체적인 정보 유지와 데이터 요청 후 매끄러운 라우팅 작업을 하고 있습니다.

<br><br>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [x] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.

2022-07-23 09:37 UTC, numeru requested changes
일단 request changes 로 두겠습니다!
수고하셨습니다~

2022-07-23 09:37 UTC, numeru commented on src/pages/MessageBox/index.tsx
> +				{messageList && messageList.length === 0 && (
이 코드를 포함해서 `a && a` 로 하신 코드가 여러 개 보이는데 `a?.` 가 가능한 부분은 바꿔보셔도 간결해서 좋아보입니다!

2022-07-23 09:37 UTC, numeru commented on src/pages/MessageDetail/index.tsx
> +				detailTreeName={state === 'favorite' ? '즐겨찾기' : messageDetail?.treeResponseDto.name}
코드를 보니 메시지 링크를 눌러 메시지 디테일 페이지로 이동할 때
`state` 를 함께 보내서 나무 폴더에서 온건지, 즐겨찾기에서 온건지 구분하도록 하신 것 같은데,

버튼을 통해 이동하지 않고 링크를 저장해뒀다가 바로 들어올 수도 있지 않을까요?
그러면 `state` 가 안넘어 와서 이 경우 무조건 나무 폴더에서 온 걸로 정해질텐데 괜찮을까 해서요!

아예 즐겨찾기 메시지함은 라우터 링크를 따로 만들어 분리해도 좋을 것 같습니다~

2022-07-23 09:37 UTC, numeru commented on src/pages/MessageBox/index.tsx
> +									message={res}
이건 궁금한건데, 변경이 가능한 데이터를 `map` 으로 돌릴 때 `idx` 를 `key` 로 쓰면 안되는 이유가
리액트는 리렌더링 후 `key` 를 이용해 돔 요소를 식별하고 그에 맞게 보여주기 때문인데
앞에 `message-box-message` 를 붙인 것으로 위의 문제가 해결될 수 있을까요?

혹시 잘못 알고 있다면 말씀 부탁드립니다!

2022-07-23 09:37 UTC, numeru commented on src/pages/TreeDetail/index.tsx
>  					</S.NextButton>
사용자가 클릭 했을 때 링크가 바뀌는 요소는 `Link` 태그를 사용하는 것이
웹 접근성이나 태그의 용도를 생각했을 때 조금 더 적절한 것 같긴 합니다!
같이 실행되어야 하는 로직은 `useEffect` 의 `clear fucntion` 을 이용하면 될 것 같은데, 저도 더 생각해보고 확실히 말씀 드리겠습니다!
혹시 이 부분에 대해 잘 아신다면 말씀 부탁드리고, 지금은 고려만 부탁드립니다~

2022-07-23 09:37 UTC, numeru commented on src/pages/MessageBox/index.tsx
> +		}
여기서 `return` 은 없어도 괜찮아 보입니다!

2022-07-23 09:54 UTC, leechoiswim1 commented on src/pages/MessageBox/index.tsx
> +									message={res}
맞습니다 id로 수정하겠습니다.

2022-07-23 10:02 UTC, leechoiswim1 commented on src/pages/MessageDetail/index.tsx
> +				detailTreeName={state === 'favorite' ? '즐겨찾기' : messageDetail?.treeResponseDto.name}
음 아예 router를 분리하는것이 좋겠네요! 좋은아이디어입니다 반영해보도록하겠습니다!

2022-07-24 05:24 UTC, youngminss approved these changes

2022-07-24 05:40 UTC, merged