[Feat] 메시지함 사이드 서랍 컴포넌트 스타일링
YAPP-Github/20th-Web-Team-1-FE pull request #21
Opened 2022-07-03 12:29 UTC by youngminss

### 💡 다음 이슈를 해결했어요.

- #20 

<br><br>

### 💡 필요한 후속작업이 있어요.

- 서랍에서 각 프로젝트 폴더 아이템 더보기 아이템 박스(편집하기, 삭제하기 버튼) 스타일링을 추가해야 합니다.
  - 각 나무 폴더 아이템 "..." 바로 아래에 박스 아이템을 위치 시키고 싶은데 좋은 아이디어 있다면 첨언 부탁드립니다 ~ ! 🧐
  - 각 나무 폴더 아이템 요소마다 더보기 아이템 박스를 배치시키는 것은 아무래도 비효율적인 것 같아서, 모달을 이용한 방식을 생각하고 있는데, 정확한 좌표를 어떻게 적용 시킬 수 있을지 고민입니다.

- 이번 PR 까지는 기존 컴포넌트 디렉터리 구성이 그대로 적용되서 올라가도록 하겠습니다. 수정해야할 컴포넌트 디렉터리 양이 좀 되서, 새로운 PR 단위로 올리겠습니다 ~ !

<br><br>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [x] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.

2022-07-04 06:03 UTC, numeru requested changes
작업하시느라 고생많으셨습니다!

말씀해주신 더보기 아이템 박스 모달 배치는 아무래도 적절한 좌표를 찾아서 `positon: absolute` 등으로 배치시키는건 어려울 것 같습니다!
폴더 아이템 요소마다 배치하는 것이 비효율적인 것 같다고 말씀해주셨는데, 저는 괜찮다고 생각합니다!

```
const SomeComponent = () => {
  const [ isMenuVisible, setIsMenuVisible ] = useState(false);
  
  <SomeContainer>
    <TreeFolderItem />
    { isMenuVisible && <TreeFolderSubMenu /> }
  </SomeContainer>
}
```

이런 느낌으로 두 컴포넌트를 한번 더 감싸는 공통 컴포넌트를 만들면 어떨까요?
이렇게 해야 스타일로 배치하기 쉬울 것 같습니다!
제안일 뿐이니 편하게 고려해주시고 지난 오프라인 모임에서 결정된 스타일, 폴더 컨벤션은 추후 적용 부탁드려요~

2022-07-04 06:03 UTC, numeru commented on src/pages/Message/index.tsx
> +};
`Message` 페이지는 임시로 만드신거고 이후 수임님이 여기에 메세지 리스트를 구현하시는 걸로 이해하면 될까요?

2022-07-04 06:03 UTC, numeru commented on src/components/shared/Modal/ModalFrame.tsx
> +			<S.ModalBackDrop show={onModal} onClick={() => setOnModal(false)}></S.ModalBackDrop>
이건 개인차이긴 한데 `props` 로 받는 `onModal` 과 `setOnModal` 의 네이밍이 사용 목적을 유추하기 약간 어려운 것 같긴 합니다!

아래에 `SideDrawerView` 컴포넌트가 `props` 로 받는 `onMenuMoreModal` 과 `setOnMenuMoreModal` 도 그렇구요!

꼭 바꾸실 필요는 없지만 가능하시면 고려 부탁드려요~

2022-07-04 06:03 UTC, numeru commented on src/components/shared/Modal/SideDrawer/SideDrawerView.tsx
> +					</S.TreeFolderListTopMenu>
`h1~h6`의 헤딩 태그는 웹 접근성 상 계층 구조를 가지도록 마크업 해야 하는 것으로 알고 있습니다!
`{username}의 메시지함` 을 `h2`로, `나무 폴더` 를 `h3` 로 하셨다면,
중간에 있는 `나에게 온 메시지`, `즐겨 찾기` 링크도 모두 `h3` 태그로 지정하시는 것이 자연스럽지 않을까 생각합니다!

그리고 이렇게 되면 `section` 태그의 사용이 적절한지도 고민이 필요하겠네요!

아래 관련 링크 첨부합니다~

https://seulbinim.github.io/WSA/heading.html#%EC%A0%9C%EB%AA%A9-%EA%B4%80%EB%A0%A8-%EC%9A%94%EC%86%8C

2022-07-04 06:03 UTC, numeru commented on src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItemView.tsx
> +		<S.TreeFolderItem>
수임님께서 메시지 리스트를 어떻게 구현하실지 모르지만, 저희 메시지 함이 나무 별로 선택이 가능하기 때문에
가장 간단하게 구현하는 방법으로 메시지 함 주소를 `/messages/:treeId` 로 해서
각각에 맞는 treeId를 주소에서 받아와 메시지 조회 api를 호출하는 것이 생각나는데요!

그러려면 `TreeFolderItem` 은 `Link` 태그여야 할 것 같습니다.

이부분은 수임님과 상의 부탁드려요~

2022-07-07 16:55 UTC, youngminss commented on src/pages/Message/index.tsx
> +};
네, 메시지 리스트는 @leechoiswim1  님이 구현하실 것 같습니다
현재 올라가는 `Message 페이지` 는 Side Drawer 컴포넌트 UI 를 구현하느라 먼저 생성했었습니다 ~ !

2022-07-07 17:00 UTC, youngminss commented on src/components/shared/Modal/ModalFrame.tsx
> +			<S.ModalBackDrop show={onModal} onClick={() => setOnModal(false)}></S.ModalBackDrop>
의견 감사합니다.
고려해보고 변경해보겠습니다 ~ !

2022-07-07 17:00 UTC, youngminss commented on src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItemView.tsx
> +		<S.TreeFolderItem>
네 의견 감사합니다 ~ !

2022-07-07 17:07 UTC, youngminss commented on src/components/shared/Modal/SideDrawer/SideDrawerView.tsx
> +					</S.TreeFolderListTopMenu>
> https://seulbinim.github.io/WSA/heading.html#%EC%A0%9C%EB%AA%A9-%EA%B4%80%EB%A0%A8-%EC%9A%94%EC%86%8C

좋은 레퍼런스 공유 감사합니다 👍 
좀 더 계층구조를 신경 쓴 구조로 변경해보겠습니다 ~ !

2022-07-07 18:11 UTC, youngminss commented
> 작업하시느라 고생많으셨습니다!
> 
> 말씀해주신 더보기 아이템 박스 모달 배치는 아무래도 적절한 좌표를 찾아서 `positon: absolute` 등으로 배치시키는건 어려울 것 같습니다! 폴더 아이템 요소마다 배치하는 것이 비효율적인 것 같다고 말씀해주셨는데, 저는 괜찮다고 생각합니다!
> 
> ```
> const SomeComponent = () => {
>   const [ isMenuVisible, setIsMenuVisible ] = useState(false);
>   
>   <SomeContainer>
>     <TreeFolderItem />
>     { isMenuVisible && <TreeFolderSubMenu /> }
>   </SomeContainer>
> }
> ```
> 
> 이런 느낌으로 두 컴포넌트를 한번 더 감싸는 공통 컴포넌트를 만들면 어떨까요? 이렇게 해야 스타일로 배치하기 쉬울 것 같습니다! 제안일 뿐이니 편하게 고려해주시고 지난 오프라인 모임에서 결정된 스타일, 폴더 컨벤션은 추후 적용 부탁드려요~

말씀해주신 방식으로도 구현이 가능하고 방법 중 하나 인 것 같습니다.
페이지 내에서 하나의 메뉴 더보기 버튼이 사용되면 고려해보려 했습니다.

다만, 저희는 각 메뉴 아이템 당 메뉴 더보기가 있다보니 현재는 최대 4개의 아이템만 있어서 진행해도 될 것 처럼 보이지만, 만약 여러 개의 아이템일 경우 비례적으로 더보기 아이템 박스가 여러 개가 생긴다고 생각할 수 있는데 이것이 괜찮은 방법인 건가 생각이 들었습니다.

더불어 만약 언급해주신 방법대로 진행할 경우, 각 폴더 아이템 별로 더 보기를 클릭한 아이템에 대해서만 더 보기 박스가 보이도록 `isMenuVisible` 상태 값을 어떻게 관리할까 고민이 됩니다.

모달 방식으로 사용할 경우, 위치 계산 방법이 당장 떠오르진 않지만 하나의 더 보기 박스만 관리하면 될 것 같아서 편할 것이라 생각이 들었네요 ..! 좀 더 고민해보겠습니다 🧐

2022-07-07 18:30 UTC, merged