Feat : 마이페이지 스타일링
YAPP-Github/20th-Web-Team-1-FE pull request #9
Opened 2022-06-06 12:53 UTC by numeru

### 💡 다음 이슈를 해결했어요.

- 마이페이지 스타일링

웹 접근성을 위해 해딩 태그를 단계적으로 추가했는데 괜찮은 방법인지는 고민입니다.
컴포넌트를 잘 나눈걸지 이후에도 생각이 필요하네요.

<br><br>

### ✅ 셀프 체크리스트

- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [x] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [x] 변경 후 코드는 기존의 테스트를 통과합니다.
- [x] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

2022-06-08 17:27 UTC, youngminss requested changes

2022-06-08 17:27 UTC, youngminss commented on src/components/features/MyPage/Badge/Badge.styled.ts
> +
앞으로 반응형 스타일링이 많이 들어갈 것을 생각해봤습니다.

현재는 특정 px 값으로 breakpoint 를 잡고 있는데, 이를 theme 에 설정해서 사용하는 건 어떨까요 ?

루트 글꼴 크기를 `16px` 로 설정하고 breakpoint 마다 rem 단위로 설정해보는 방식이 있더라구요 !

아래는 그와 관려된 포스팅입니다 !

https://dev.to/sobhandash/media-queries-and-breakpoints-2022-4gkm

2022-06-08 17:27 UTC, youngminss commented on src/components/features/MyPage/MyContents/MyContents.tsx
> +
`hidden 속성`이 어떤 의미로 사용되었는지 알 수 있을까요 ?

웹 접근성에 대해 신경을 써보려고 하신 것이면, 저도 아직 웹 접근성에 대해서는 잘 알지 못하지만, 현재 사용된 방식과 의도하신 부분이 맞는 지 한 번 확인해보아도 좋을 것 같습니다 !

https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/hidden

이번 프로젝트 통해서 웹 접근성 측면도 고려해보는 시간이 되었으면 좋겠네요.

2022-06-08 17:27 UTC, youngminss commented on src/components/features/MyPage/MyContents/MyContents.tsx
> +
당장은 map 함수에서 `key` 값을 `idx` 로 할당이 되었는데, 이 부분은 현재 구현이 시급하기 때문에 적용하신 걸로 알고 있겠습니다 !

이후에는 더 개선된 방식으로 변형해보죠 !

2022-06-08 17:27 UTC, youngminss commented on src/components/features/MyPage/MySetting/MySetting.tsx
> +
영광님은 타입 선언 시에 `type` 키워드를 사용하시는 것 같더라구요 !
`interface` 키워드를 사용하진 않고 `type` 키워드를 사용하는 이유가 혹시 있다면 궁금합니다 ! ( 이건 단순 궁금증입니다 🙂 )

2022-06-08 17:27 UTC, youngminss commented on src/constants/badge.ts
> +];
상수 분리하신 것 좋네요 ! 👍

2022-06-08 17:39 UTC, youngminss commented
마이페이지 스타일링 작업하시느라 고생하셨습니다.

현재 올려주신 PR 에 대해 제가 질문드리고 싶은 메시지를 남겼습니다.

approve 하는 것이 나을 수도 있겠지만, 남긴 메시지에 대해 다시 한 번 생각해보시면 좋을 것 같다고 생각해서 다시 한 번 Request 해보겠습니다 !

웹 접근성 고려하셔서 텍스트 숨김 처리하는 것에 대해, 참고해보시면 좋을 것 같아 첨부 자료 하나 남깁니다.

https://velog.io/@ursr0706/%EC%9B%B9-%EC%A0%91%EA%B7%BC%EC%84%B1%EC%9D%84-%EA%B3%A0%EB%A0%A4%ED%95%98%EC%97%AC-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%88%A8%EA%B8%B0%EA%B8%B0

2022-06-09 03:44 UTC, numeru commented on src/components/features/MyPage/Badge/Badge.styled.ts
> +
> 앞으로 반응형 스타일링이 많이 들어갈 것을 생각해봤습니다.
> 
> 현재는 특정 px 값으로 breakpoint 를 잡고 있는데, 이를 theme 에 설정해서 사용하는 건 어떨까요 ?
> 
> 루트 글꼴 크기를 `16px` 로 설정하고 breakpoint 마다 rem 단위로 설정해보는 방식이 있더라구요 !
> 
> 아래는 그와 관려된 포스팅입니다 !
> 
> https://dev.to/sobhandash/media-queries-and-breakpoints-2022-4gkm

첨부해주신 방식도 좋은 것 같습니다!
다만 현재는 모바일 사이즈의 화면만 고려 하고 디자인이 나오고 있기 때문에, media query와 breakpoint를 사용하는 일이 많지는 않을 것 같습니다!

저희가 대략적으로 200px~480px 까지 자연스러워 보이게 만들고 있어서, breakpoint를 이 안에서 px로 간단하게 하는 것이 개인적으로는 좋아보입니다!
제가 여기서 media query를 사용한건 300px과 450px에서 같은 구현을 해도 다른 결과가 나왔기 때문인데, 만약 theme에 설정해서 사용한다면 어느 지점으로 고정할지도 고민이네요.

2022-06-09 03:44 UTC, numeru commented on src/components/features/MyPage/MyContents/MyContents.tsx
> +
> `hidden 속성`이 어떤 의미로 사용되었는지 알 수 있을까요 ?
> 
> 웹 접근성에 대해 신경을 써보려고 하신 것이면, 저도 아직 웹 접근성에 대해서는 잘 알지 못하지만, 현재 사용된 방식과 의도하신 부분이 맞는 지 한 번 확인해보아도 좋을 것 같습니다 !
> 
> https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/hidden
> 
> 이번 프로젝트 통해서 웹 접근성 측면도 고려해보는 시간이 되었으면 좋겠네요.

`hidden` 속성은 `GlobalStyle` 에 있는 것 처럼 웹 접근성을 위해 마크업 상에 존재는 하지만 스타일로 가려서 화면에 보이지 않는 태그를 만들기 위해 사용하였습니다!

그런데 첨부해주신 글을 보고 다시 확인해보니 hidden 속성 자체가 화면에 아예 렌더링 되지 않고 스크린 리더에서도 인식되지 않게 만드네요.
`className="a11y-hidden"` 등으로 바꿔야겠습니다!

해딩 태그와 웹 접근성에 관한 글 아래 첨부드립니다. 같이 읽어보셔도 좋을 것 같아요!

https://seulbinim.github.io/WSA/heading.html#%EC%A0%9C%EB%AA%A9-%EC%9A%94%EC%86%8C-h1-h6

https://nuli.navercorp.com/community/article/1133024

2022-06-09 03:44 UTC, numeru commented on src/components/features/MyPage/MyContents/MyContents.tsx
> +
> 당장은 map 함수에서 `key` 값을 `idx` 로 할당이 되었는데, 이 부분은 현재 구현이 시급하기 때문에 적용하신 걸로 알고 있겠습니다 !
> 
> 이후에는 더 개선된 방식으로 변형해보죠 !

네 배지 기능은 3차로 알고 있기도 하고, `map`으로 만든 리스트여도 수정, 삭제 되지 않는다면 `idx`를 `key`로 사용해도 문제 없는 것으로 알고 있어서 이렇게 해두었습니다!

그래도 혹시 모르니 `name` 을 `key`로도 사용하는 것이 좋아보이네요!

2022-06-09 03:44 UTC, numeru commented on src/components/features/MyPage/MySetting/MySetting.tsx
> +
> 영광님은 타입 선언 시에 `type` 키워드를 사용하시는 것 같더라구요 ! `interface` 키워드를 사용하진 않고 `type` 키워드를 사용하는 이유가 혹시 있다면 궁금합니다 ! ( 이건 단순 궁금증입니다 🙂 )

네 저도 `type` 과 `interface` 에 대해 비교가 많은걸로 알고 있는데, 기능적으로 세세한 몇몇 차이는 있지만 대부분의 상황에서 유의미한 차이는 없는걸로 알고 있습니다!
그래서 저도 큰 이유를 갖고 사용하는 것은 아니지만, vscode 상에서 마우스를 올렸을 때 `interface`는 내부 속성이 보이지 않지만 `type`은 보여서 사용합니다!

그리고 제 개인적인 코드 스타일 상, `interface`는 class와 관련해서 사용하고, `type`은 그 외 여러 타입을 지정할 때 사용하면서 최대한 둘의 역할을 분명히 구분지으려 하고 있습니다!

그래도 다른 두분께서 `interface`를 사용하시는 이유가 있거나, 코드 컨벤션 상 `interface` 로 통일했으면 하신다면 바꿔도 괜찮습니다!

2022-06-09 03:44 UTC, numeru commented on src/constants/badge.ts
> +];
👍👍

2022-06-09 03:46 UTC, numeru commented
리뷰 감사합니다! 말씀해주신 부분 반영해서 다시 commit 하겠습니다!

2022-06-10 04:22 UTC, merged